Basic teleportation interactions
argian/ArtEye.2 pull request #18
Opened 2024-11-26 15:05 UTC by Kimel-PK

2024-11-27 01:14 UTC, m-biernat requested changes
Async method in SceneLoader was private on purpose.

2024-11-27 01:14 UTC, m-biernat commented on Assets/_Project/Scripts/Scene/SceneLoader.cs
> +        public async UniTask LoadSceneAsync(SceneLink link)
Should remain private because it is not meant to be called directly. LoadScene() with OnLoadStart and OnLoadEnd events is the intended way to load scenes because of safety checks (and other reasons).

2024-11-27 19:38 UTC, Kimel-PK commented on Assets/_Project/Scripts/Scene/SceneLoader.cs
> +        public async UniTask LoadSceneAsync(SceneLink link)
But I need to wait for scene load and I cannot do it any other way

2024-11-28 01:15 UTC, m-biernat approved these changes
LGTM

2024-11-28 01:15 UTC, merged